services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mensah.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: mensah.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mensah-db  # <-- Replace with the exact name you give your DB
          property: connectionString
